import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>PokeTB</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section id="landing" className="bg-red-500">
        <nav className="flex flex-row mx-auto w-full max-w-6xl justify-between py-2 px-5 h-36">
            <div className="flex items-center">
                <figure className="w-14 h-14 flex items-center justify-center">
                    <Image id="poke-logo" src="./assets/noun-pokeball-594337.svg" width={48} height={48} alt="" />
                </figure>
                <h1 className="text-neutral-900 text-2xl font-semibold">PokeTB</h1>
            </div>
            <ul className="flex items-center justify-between">
                <li className="mx-3">
                   <a href="#" className="text-lg font-medium text-neutral-900">
                      Home
                    </a> 
                </li>
                <li className="mx-3">
                    <a href="#" className="text-lg font-medium text-neutral-900">
                        Dark/Light Icon 
                    </a> 
                </li>
                <li className="mx-3">
                    <a href="#" className="text-lg font-medium text-neutral-900">
                        Log In
                    </a> 
                </li>
                <li className="mx-3">
                    <a href="#" className="text-lg font-medium text-neutral-900">
                        Sign Up
                    </a> 
                </li>
            </ul>
        </nav>
        <header id="search">
            <div className="flex flex-col items-center py-6 mx-3">
                <h1 className="text-neutral-900 font-bold text-7xl text-center mb-6">Choose a Pokemon!</h1>
                <div className="flex p-2 items-center border-2 border-white rounded-full bg-white w-full max-w-xl">
                    <input type="text" className="w-full pr-8 text-2xl indent-5 outline-none" placeholder="Enter a name or number"/>
                    <button type="submit" className="bg-white">
                      <Image id="search-icon" className="mr-3" src="./assets/search_icon.svg" width={32} height={32} alt="" />
                    </button>
                </div>
            </div>
        </header>
    </section>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
}
