import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import type { InferGetStaticPropsType, GetStaticProps } from "next";

import { api } from "~/utils/api";

type PokemonResult = {
  name: string;
  url: string;
  details?: any
};

type PokemonList = {
  count: number;
  next?: string;
  previous?: string;
  results: PokemonResult[];
};

// export function PokemonCardDisplay({ pokemonList }) {
//   return (
//     <ul>
//       {pokemonList.map((pokemon) => (
//         <li>{pokemon.name}</li>
//       ))}
//     </ul>
//   )
// }

export const getStaticProps: GetStaticProps =
  (async (context) => {
    const res = await fetch("https://pokeapi.co/api/v2/pokemon/?limit=1010");
    const pokemonList = await res.json();

    const pokemonListPromises = pokemonList.results.map(async (pokemon: PokemonResult) => {
      const resPokemonInfo = await fetch(
        `${pokemon.url}`
      );
      return await resPokemonInfo.json();
      
    });

    const pokemonData = await Promise.all(pokemonListPromises);

    pokemonList.results.forEach((pokemonInfo: { details: any; }, index: number) => {
      pokemonInfo.details = pokemonData[index];
    });

    return { props: { pokemonList } };
  }) satisfies GetStaticProps<{
    pokemonList: PokemonList;
  }>;

// function PokemonCardDisplay({ pokemonList }: InferGetStaticPropsType<typeof getStaticProps>) {
//   return (
// <ul>
//   {pokemonList.results.map((pokemon: PokemonResult) => (
//     <li>{pokemon.name}</li>
//   ))}
// </ul>
//   )
// }

// interface PokemonListInfoProps {
//   pokemonList: PokemonList;
// }

// const PokemonListInfo: React.FC<PokemonListInfoProps> = ({ pokemonList }) => {
//   return (
//     <div>
//       {pokemonList.count}
//     </div>
//   );
// };

export default function Home({
  pokemonList,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>PokeTB</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section id="landing" className="bg-red-500">
        <nav className="mx-auto flex h-24 w-full max-w-6xl flex-row justify-between px-5 py-2">
          <div className="flex items-center">
            <figure className="flex h-14 w-14 items-center justify-center">
              <Image
                id="poke-logo"
                src="./assets/noun-pokeball-594337.svg"
                width={48}
                height={48}
                alt=""
              />
            </figure>
            <h1 className="text-2xl font-semibold text-neutral-900">PokeTB</h1>
          </div>
          <ul className="flex items-center justify-between">
            <li className="mx-3">
              <a href="#" className="text-lg font-medium text-neutral-900">
                Home
              </a>
            </li>
            <li className="mx-3">
              <a href="#" className="text-lg font-medium text-neutral-900">
                Dark/Light Icon
              </a>
            </li>
            <li className="mx-3">
              <a href="#" className="text-lg font-medium text-neutral-900">
                Log In
              </a>
            </li>
            <li className="mx-3">
              <a href="#" className="text-lg font-medium text-neutral-900">
                Sign Up
              </a>
            </li>
          </ul>
        </nav>
        <header id="search">
          <div className="mx-3 flex flex-col items-center py-6">
            <h1 className="mb-6 text-center text-7xl font-bold text-neutral-900">
              Choose a Pokemon!
            </h1>
            <div className="flex w-full max-w-xl items-center rounded-full border-2 border-white bg-white p-2">
              <input
                type="text"
                className="w-full pr-8 indent-5 text-2xl outline-none"
                placeholder="Enter a name or number"
              />
              <button type="submit" className="bg-white">
                <Image
                  id="search-icon"
                  className="mr-3"
                  src="./assets/search_icon.svg"
                  width={32}
                  height={32}
                  alt=""
                />
              </button>
            </div>
          </div>
        </header>
      </section>
      {/* <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div>
      </main> */}
      <section id="results">
        <div className="w-full py-12">
          <div className="mx-auto my-0 w-full max-w-6xl">
            <div className="flex flex-col items-center">
              <div className="flex w-full flex-col items-center bg-amber-100">
                <h1 className="text-4xl font-bold ">Advanced Search</h1>
                <div id="filter">
                  <h3 className="text-center text-xl">Filter by Type</h3>
                  <div className="my-2 flex w-full max-w-5xl flex-wrap items-center justify-center">
                    {/* map types */}
                    <div className="mx-2 my-2 flex justify-between">
                      <input type="checkbox" name="type-filter" id="" />
                      <div className="bg-normal border-normal-border mx-1.5 rounded-3xl border px-3 py-1 text-white">
                        NORMAL
                      </div>
                    </div>
                    <div className="mx-2 my-2 flex justify-between">
                      <input type="checkbox" name="type-filter" id="" />
                      <div className="bg-normal border-normal-border mx-1.5 rounded-3xl px-3 py-1 text-white">
                        NORMAL
                      </div>
                    </div>
                    <div className="mx-2 my-2 flex justify-between">
                      <input type="checkbox" name="type-filter" id="" />
                      <div className="bg-normal border-normal-border mx-1.5 rounded-3xl px-3 py-1 text-white">
                        NORMAL
                      </div>
                    </div>
                    <div className="mx-2 my-2 flex justify-between">
                      <input type="checkbox" name="type-filter" id="" />
                      <div className="bg-normal border-normal-border mx-1.5 rounded-3xl px-3 py-1 text-white">
                        NORMAL
                      </div>
                    </div>
                    <div className="mx-2 my-2 flex justify-between">
                      <input type="checkbox" name="type-filter" id="" />
                      <div className="bg-normal border-normal-border mx-1.5 rounded-3xl px-3 py-1 text-white">
                        NORMAL
                      </div>
                    </div>
                    <div className="mx-2 my-2 flex justify-between">
                      <input type="checkbox" name="type-filter" id="" />
                      <div className="bg-normal border-normal-border mx-1.5 rounded-3xl px-3 py-1 text-white">
                        NORMAL
                      </div>
                    </div>
                    <div className="mx-2 my-2 flex justify-between">
                      <input type="checkbox" name="type-filter" id="" />
                      <div className="bg-normal border-normal-border mx-1.5 rounded-3xl px-3 py-1 text-white">
                        NORMAL
                      </div>
                    </div>
                    <div className="mx-2 my-2 flex justify-between">
                      <input type="checkbox" name="type-filter" id="" />
                      <div className="bg-normal border-normal-border mx-1.5 rounded-3xl px-3 py-1 text-white">
                        NORMAL
                      </div>
                    </div>
                    <div className="mx-2 my-2 flex justify-between">
                      <input type="checkbox" name="type-filter" id="" />
                      <div className="bg-normal border-normal-border mx-1.5 rounded-3xl px-3 py-1 text-white">
                        NORMAL
                      </div>
                    </div>
                    <div className="mx-2 my-2 flex justify-between">
                      <input type="checkbox" name="type-filter" id="" />
                      <div className="bg-normal border-normal-border mx-1.5 rounded-3xl px-3 py-1 text-white">
                        NORMAL
                      </div>
                    </div>
                    <div className="mx-2 my-2 flex justify-between">
                      <input type="checkbox" name="type-filter" id="" />
                      <div className="bg-normal border-normal-border mx-1.5 rounded-3xl px-3 py-1 text-white">
                        NORMAL
                      </div>
                    </div>
                    <div className="mx-2 my-2 flex justify-between">
                      <input type="checkbox" name="type-filter" id="" />
                      <div className="bg-normal border-normal-border mx-1.5 rounded-3xl px-3 py-1 text-white">
                        NORMAL
                      </div>
                    </div>
                    <div className="mx-2 my-2 flex justify-between">
                      <input type="checkbox" name="type-filter" id="" />
                      <div className="bg-normal border-normal-border mx-1.5 rounded-3xl px-3 py-1 text-white">
                        NORMAL
                      </div>
                    </div>
                    <div className="mx-2 my-2 flex justify-between">
                      <input type="checkbox" name="type-filter" id="" />
                      <div className="bg-normal border-normal-border mx-1.5 rounded-3xl px-3 py-1 text-white">
                        NORMAL
                      </div>
                    </div>
                    <div className="mx-2 my-2 flex justify-between">
                      <input type="checkbox" name="type-filter" id="" />
                      <div className="bg-normal border-normal-border mx-1.5 rounded-3xl px-3 py-1 text-white">
                        NORMAL
                      </div>
                    </div>
                    <div className="mx-2 my-2 flex justify-between">
                      <input type="checkbox" name="type-filter" id="" />
                      <div className="bg-normal border-normal-border mx-1.5 rounded-3xl px-3 py-1 text-white">
                        NORMAL
                      </div>
                    </div>
                    <div className="mx-2 my-2 flex justify-between">
                      <input type="checkbox" name="type-filter" id="" />
                      <div className="bg-normal border-normal-border mx-1.5 rounded-3xl px-3 py-1 text-white">
                        NORMAL
                      </div>
                    </div>
                    <div className="mx-2 my-2 flex justify-between">
                      <input type="checkbox" name="type-filter" id="" />
                      <div className="bg-normal border-normal-border mx-1.5 rounded-3xl px-3 py-1 text-white">
                        NORMAL
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <h3 className="text-center text-xl">Sort by:</h3>
              <select id="sort" className="p-2">
                <option value="NUMBER_LOW_TO_HIGH" selected>
                  Number - Low to High
                </option>
                <option value="NUMBER_HIGH_TO_LOW">Number - High to Low</option>
                <option value="ALPHA_A_TO_Z">Name - A to Z</option>
                <option value="ALPHA_Z_TO_A">Name - Z to A</option>
              </select>
              <button
                type="button"
                className="w-1/5 rounded-3xl bg-red-500 p-3 text-white"
              >
                Go!
              </button>
            </div>
            <div className="flex w-full">
              <ul>
                {console.log(pokemonList)}
                {pokemonList.results.map((pokemon: PokemonResult) => (
                  <li>{pokemon.name} - {pokemon.details.types[0].type.name}</li>
                ))}
                {/* {pokemonList.results} */}
              </ul>
              {/* <i class="fas fa-spinner results__loading--spinner"></i> */}
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
